# Generated by Django 5.2.7 on 2025-11-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ans', models.CharField(max_length=200)),
                ('tiempo_respuesta_max', models.PositiveIntegerField()),
                ('tiempo_resolucion_max', models.PositiveIntegerField()),
                ('personalizacion', models.TextField(blank=True)),
                ('fecha_vigencia', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
                ('horario_atencion', models.JSONField(default=dict, help_text="Ej: {'lunes': ['09:00-18:00']}")),
            ],
            options={
                'verbose_name_plural': 'ANS',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('funcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Funciones',
            },
        ),
        migrations.CreateModel(
            name='PlantillaFormulario',
            fields=[
                ('formulario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plantilla', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('campo_formulario', models.JSONField(default=list, help_text="Ej: [{'nombre': 'urgencia', 'tipo': 'select', 'opciones': ['Alta', 'Media']}]")),
            ],
            options={
                'verbose_name_plural': 'Plantillas de Formulario',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tiempo_resolucion', models.DurationField(blank=True, null=True)),
                ('datos_formulario', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('etiqueta', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('texto', 'Texto Corto'), ('textarea', 'Texto Largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('seleccion', 'Selección'), ('checkbox', 'Casilla'), ('radio', 'Radio'), ('archivo', 'Archivo')], max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_detalle', to='gestion.plantillaformulario')),
            ],
            options={
                'verbose_name_plural': 'Campos de Formulario',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='en_progreso', max_length=20)),
                ('ans', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto_ans', to='gestion.ans')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='gestion.cliente')),
                ('plantilla_formulario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto_relacionado', to='gestion.plantillaformulario')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='plantillaformulario',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_relacionada', to='gestion.proyecto'),
        ),
    ]
